### ISSUE TITLE
How to disable pressing space to go to next page?

### ISSUE THREAD

**Issue by Minibus93** [koodo-reader/koodo-reader#260] opened 2021-11-04 17:21 UTC
Hello, thank you for realizing this software. I'm using this to read uni books and I find it kinda perfect. It' easy and modern!

However, when I try to take a note, while writing, I press the spacebar and it goes to the next page, basically killing the note I was taking.

Is there any way to disable spacebar "go to next page" shortcut? 

Am I taking notes in the wrong way?

**Comment by troyeguo** [comment] 2021-11-05 00:59
This bug has been fixed in the latest 1.3.4 version. Which version or browser are you using?

**Comment by Minibus93** [comment] 2021-11-05 10:09
Before writing this question I just updated to 1.3.4 and after the installation on w10 a pop up said something like "congrats, you successfully upgraded to 1.3.4!"

**Comment by troyeguo** [comment] 2021-11-05 10:21
You can try to backup your data and delete this folder: C:\Users\[username]\AppData\Roaming\koodo-reader. And see if this problem exist?

**Comment by troyeguo** [comment] 2021-11-05 10:48
We will consider to remove space key shortcut in the future updates

**Comment by Minibus93** [comment] 2021-11-05 11:07
Removing the folder fixed the spacebar issue, however, now I'm unable to go to next/previous page using left and right arrow keys. 
Arrow keys only works if I click on the page and then use the arrow key. However this only work for going 1 page forward/backward. To do another page it requires another click

Is this intended or there are ways to restore previous arrow keys behavior?

**Comment by troyeguo** [comment] 2021-11-05 11:19
Thanks for the feedback, this is a bug. we will fix it in the next update

**Comment by thenoobtester** [comment] 2021-11-14 18:01
>  I'm unable to go to next/previous page using left and right arrow keys.
Arrow keys only works if I click on the page and then use the arrow key. However this only work for going 1 page forward/backward. To do another page it requires another click

I can confirm this.

**Comment by NegassaB** [comment] 2021-11-22 09:31
> Hello, thank you for realizing this software. I'm using this to read uni books and I find it kinda perfect. It' easy and modern!
> 
> However, when I try to take a note, while writing, I press the spacebar and it goes to the next page, basically killing the note I was taking.
> 
> Is there any way to disable spacebar "go to next page" shortcut?
> 
> Am I taking notes in the wrong way?

I can confirm this is still present in version 1.3.4.

Other than that it's one of the greatest software I've ever used and seen. :+1:

**Comment by troyeguo** [comment] 2021-11-29 12:34
Please update to 1.3.5, and see if this bug still exsits

**Comment by NegassaB** [comment] 2021-11-29 13:45
> Please update to 1.3.5, and see if this bug still exsits

I've just updated, it seems to have been solved. I'll return with more information after testing it for the next 2 days.

Again great software, please keep at it :+1:

**Comment by Minibus93** [comment] 2021-11-29 15:56
Seems solved to me too!

Will test it more in the next two days and update this reply!

**Comment by NegassaB** [comment] 2021-12-01 12:05
> > Please update to 1.3.5, and see if this bug still exsits
> 
> I've just updated, it seems to have been solved. I'll return with more information after testing it for the next 2 days.
> 
> Again great software, please keep at it +1

I can now confirm update 1.3.5 has solved the issue.

Thank you for this great software :+1:

**Comment by NegassaB** [comment] 2021-12-26 12:52
I'm sorry to be the bearer of bad news but this bug is still present in version 1.3.9. although not as frequent as it was in version 1.3.3 and version 1.3.4.

**Comment by troyeguo** [comment] 2021-12-27 12:37
> I'm sorry to be the bearer of bad news but this bug is still present in version 1.3.9. although not as frequent as it was in version 1.3.3 and version 1.3.4.

Thanks for the feedback

**Comment by troyeguo** [comment] 2022-01-02 11:17
> I'm sorry to be the bearer of bad news but this bug is still present in version 1.3.9. although not as frequent as it was in version 1.3.3 and version 1.3.4.

Please update to 1.4.0 to see if this bug still exists. This bug still exists in some rare scenarios though. Like when opening books in the main window and open a epub book after opening a mobi/azw3/txt book. Other than that, we can't reproduce this bug for now.

**Comment by NegassaB** [comment] 2022-01-03 06:08
> > I'm sorry to be the bearer of bad news but this bug is still present in version 1.3.9. although not as frequent as it was in version 1.3.3 and version 1.3.4.
> 
> Please update to 1.4.0 to see if this bug still exists. This bug still exists in some rare scenarios though. Like when opening books in the main window and open a epub book after opening a mobi/azw3/txt book. Other than that, we can't reproduce this bug for now.

ok, I will and report back. :+1:

**Closed** 2023-12-17 07:20 UTC
Labels: question
